# Generated by Django 4.2.13 on 2024-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_of_course',
            field=models.TextField(blank='False'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_of_course',
            field=models.DateField(null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='course',
            name='fees_required',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_topics',
            field=models.PositiveSmallIntegerField(null='False'),
        ),
    ]
